### ISSUE TITLE
The last release version (1.7.9) uses deprecated urls

### ISSUE THREAD

**Issue by mwesten** [JustCarmen/fancy_research_links#15]
Hi,

The last download-release (https://github.com/JustCarmen/fancy_research_links/releases/tag/1.7.9) contains a couple of failing researchlinks (ie: wiewaswie). The latest code in the wt-1.7.9 branch contain the working/updated URLs

**Comment by JustCarmen** [comment]
Those issues have been resolved in the [latest release](https://github.com/JustCarmen/fancy_research_links/releases/tag/1.7.11).
