### ISSUE TITLE
Add http://grandeguerre.icrc.org/en/File/Search

### ISSUE THREAD

**Issue by magicsunday** [JustCarmen/fancy_research_links#7]

**Comment by JustCarmen** [comment]
This is an interesting site I haven't known it exists. But to get the search results we will have to make several sublinks to choose from (nationality and military vs civilian). But this should be possible. I will look into it.

**Comment by JustCarmen** [comment]
I decided to add it as a simple plugin with military search by default. Further search adjustments can be made at the website.
