### ISSUE TITLE
Add http://www.volksbund.de/graebersuche.html

### ISSUE THREAD

**Issue by magicsunday** [JustCarmen/fancy_research_links#8]

**Comment by JustCarmen** [comment]
At this site you can't do a search without making an account. When applying for an account they even want to know your home address. I don't see any reason why they should need that information. I don't feel like giving that information if there is no reason to.

But if you give me the url with a search filter applied (which contains a last name and a first name) I can turn it into a plugin for you which you can use for personal use. But I won't add it to the default list.
